# Copyright (c) 2025 AnonX
# Licensed under the MIT License.
# Real-time cookie watcher for dynamic sync from running Firefox instance

import os
import time
import asyncio
import logging
import sqlite3
import shutil
from pathlib import Path
from typing import Awaitable, Callable, Optional

logger = logging.getLogger(__name__)


class FirefoxCookieWatcher:
    """
    Monitors a Firefox profile directory and auto-syncs cookies to AnonX.
    Designed to work with a headless or GUI Firefox instance where the user
    is signed into YouTube.
    """

    def __init__(
        self,
        user_data_dir: str,
        cookie_output_path: str,
        check_interval: int = 60,
        youtube_domain_filter: bool = True,
        sync_callback: Optional[Callable[[], Awaitable[bool]]] = None,
    ):
        self.user_data_dir = Path(user_data_dir)
        self.cookie_output_path = Path(cookie_output_path)
        self.check_interval = check_interval
        self.youtube_domain_filter = youtube_domain_filter
        self._sync_callback = sync_callback
        self._running = False
        self._task: Optional[asyncio.Task] = None
        self._last_sync_time = 0.0
        self._last_cookie_mtime = 0.0
        self._sync_generation = 0
        self._missing_db_reported = False

    def _find_cookies_db(self) -> Optional[Path]:
        """Locate the cookies.sqlite database in the Firefox profile."""
        candidates = [
            self.user_data_dir / "cookies.sqlite",
            self.user_data_dir / "cookies.sqlite-wal",
        ]

        # Firefox profile structure is flat, cookies.sqlite is at the root
        for path in candidates:
            if path.exists() and path.is_file() and path.name == "cookies.sqlite":
                return path

        # Fallback: check if cookies.sqlite exists
        cookies_db = self.user_data_dir / "cookies.sqlite"
        if cookies_db.exists() and cookies_db.is_file():
            return cookies_db

        return None

    def _extract_cookies_to_netscape(
        self, cookies_db: Path, output_path: Path
    ) -> tuple[bool, int]:
        """
        Extract YouTube cookies from Firefox SQLite database to Netscape format.
        Returns (success, cookie_count).
        """
        temp_db = output_path.parent / f".cookies_temp_{os.getpid()}.db"

        try:
            # Ensure the target directory exists *before* any I/O.
            # Use temp_db.parent so we create the exact directory that
            # shutil.copy2 needs, regardless of how output_path is formed.
            temp_db.parent.mkdir(parents=True, exist_ok=True)

            # Remove a stale temp file from a previous crashed run.
            if temp_db.exists():
                temp_db.unlink()

            shutil.copy2(cookies_db, temp_db)

            conn = sqlite3.connect(str(temp_db))
            cursor = conn.cursor()

            if self.youtube_domain_filter:
                query = """
                    SELECT host, name, value, path, expiry, isSecure,
                           isHttpOnly, value
                    FROM moz_cookies
                    WHERE host LIKE '%youtube.com%'
                       OR host LIKE '%google.com%'
                       OR host LIKE '%googlevideo.com%'
                    ORDER BY host, name
                """
            else:
                query = """
                    SELECT host, name, value, path, expiry, isSecure,
                           isHttpOnly, value
                    FROM moz_cookies
                    ORDER BY host, name
                """

            cursor.execute(query)
            rows = cursor.fetchall()
            conn.close()

            if not rows:
                logger.warning("No cookies found in Firefox database")
                return False, 0

            lines = [
                "# Netscape HTTP Cookie File",
                "# Auto-generated by AnonX Cookie Watcher",
                "# This is a generated file! Do not edit.",
                "",
            ]

            auth_cookie_count = 0
            exported_count = 0
            encrypted_skipped = 0
            AUTH_COOKIE_NAMES = {
                "SID", "HSID", "SSID", "APISID", "SAPISID",
                "__Secure-1PSID", "__Secure-3PSID",
            }

            for row in rows:
                (
                    host_key,
                    name,
                    value,
                    path,
                    expires_utc,
                    is_secure,
                    is_httponly,
                    _,  # Firefox doesn't have encrypted_value in the same way
                ) = row

                # Firefox stores cookies in plain text in the value column
                clear_value = str(value or "")
                if not clear_value:
                    continue

                if name in AUTH_COOKIE_NAMES:
                    auth_cookie_count += 1
                exported_count += 1

                domain = host_key if not host_key.startswith(".") else host_key
                include_subdomains = "TRUE" if host_key.startswith(".") else "FALSE"
                secure = "TRUE" if is_secure else "FALSE"

                # Firefox stores expiry as Unix timestamp (seconds since 1970-01-01)
                # Already in the correct format
                if expires_utc:
                    unix_timestamp = int(expires_utc)
                else:
                    unix_timestamp = 0

                cookie_line = "\t".join([
                    domain,
                    include_subdomains,
                    path or "/",
                    secure,
                    str(unix_timestamp),
                    name,
                    clear_value,
                ])
                lines.append(cookie_line)

            if exported_count == 0 or (
                self.youtube_domain_filter and auth_cookie_count == 0
            ):
                logger.warning(
                    "Cookie watcher skipped raw export exported=%d "
                    "auth_markers=%d; yt-dlp export required",
                    exported_count,
                    auth_cookie_count,
                )
                return False, 0

            output_path.parent.mkdir(parents=True, exist_ok=True)

            temp_output = output_path.parent / f".{output_path.name}.tmp"
            with open(temp_output, "w", encoding="utf-8") as f:
                f.write("\n".join(lines) + "\n")

            if hasattr(os, "chmod"):
                try:
                    os.chmod(temp_output, 0o600)
                except Exception:
                    pass

            temp_output.replace(output_path)

            if hasattr(os, "chmod"):
                try:
                    os.chmod(output_path, 0o600)
                except Exception:
                    pass

            logger.info(
                "Cookie watcher raw export cookies=%d auth_markers=%d "
                "encrypted_skipped=%d",
                exported_count,
                auth_cookie_count,
                encrypted_skipped,
            )

            return True, exported_count

        except Exception as ex:
            logger.exception("Cookie watcher extraction failed: %s", ex)
            return False, 0
        finally:
            try:
                if temp_db.exists():
                    temp_db.unlink()
            except Exception:
                pass

    def _should_sync(self, cookies_db: Path) -> bool:
        """Check if cookies have been modified since last sync."""
        try:
            mtime = cookies_db.stat().st_mtime
            if mtime > self._last_cookie_mtime:
                self._last_cookie_mtime = mtime
                return True
            return False
        except Exception:
            return False

    async def _sync_once(self) -> bool:
        """Perform one sync operation."""
        cookies_db = self._find_cookies_db()
        if not cookies_db:
            # A profile may be created after the bot starts. Keep polling, but
            # do not turn a missing optional profile into a warning storm.
            if not self._missing_db_reported:
                logger.warning(
                    "Cookie watcher could not find Firefox cookies database in %s",
                    self.user_data_dir,
                )
                self._missing_db_reported = True
            return False

        self._missing_db_reported = False

        if not self._should_sync(cookies_db):
            return True

        if self._sync_callback is not None:
            success = bool(await self._sync_callback())
            count = 0
        else:
            success, count = await asyncio.to_thread(
                self._extract_cookies_to_netscape,
                cookies_db,
                self.cookie_output_path,
            )

        if success:
            self._last_sync_time = time.monotonic()
            self._sync_generation += 1
            if self._sync_callback is not None:
                logger.info(
                    "Cookie watcher sync completed source=yt_dlp generation=%d",
                    self._sync_generation,
                )
            else:
                logger.info(
                    "Cookie watcher sync completed cookies=%d generation=%d",
                    count,
                    self._sync_generation,
                )

        return success

    async def _watch_loop(self):
        """Background loop that monitors and syncs cookies."""
        logger.info(
            "Cookie watcher started user_data_dir=%s interval=%ds",
            self.user_data_dir,
            self.check_interval,
        )

        await asyncio.sleep(5)

        await self._sync_once()

        while self._running:
            try:
                await asyncio.sleep(self.check_interval)
                if not self._running:
                    break
                await self._sync_once()
            except asyncio.CancelledError:
                break
            except Exception as ex:
                logger.exception("Cookie watcher loop error: %s", ex)
                await asyncio.sleep(10)

        logger.info("Cookie watcher stopped")

    def start(self):
        """Start the cookie watcher background task."""
        if self._running:
            logger.warning("Cookie watcher already running")
            return

        # Ensure the output directory exists before the watch loop starts.
        try:
            self.cookie_output_path.parent.mkdir(parents=True, exist_ok=True)
        except Exception:
            pass

        self._running = True
        try:
            loop = asyncio.get_running_loop()
            self._task = loop.create_task(self._watch_loop())
        except RuntimeError:
            logger.error("Cookie watcher requires a running asyncio event loop")
            self._running = False

    def stop(self):
        """Stop the cookie watcher background task."""
        if not self._running:
            return

        self._running = False
        if self._task and not self._task.done():
            self._task.cancel()
        self._task = None

    async def force_sync(self) -> bool:
        """Force an immediate sync, bypassing mtime check."""
        cookies_db = self._find_cookies_db()
        if not cookies_db:
            return False

        self._last_cookie_mtime = 0.0
        return await self._sync_once()

    @property
    def is_running(self) -> bool:
        return self._running

    @property
    def sync_generation(self) -> int:
        return self._sync_generation

    @property
    def uses_external_exporter(self) -> bool:
        return self._sync_callback is not None


class ChromiumCookieWatcher(FirefoxCookieWatcher):
    """Watch a Chromium-family profile for cookie changes.

    Chromium stores its cookie database below ``Network/Cookies`` (newer
    profiles) or as ``Cookies`` at the profile root (older profiles).  The
    normal AnonX deployment supplies ``sync_callback`` so an external cookie
    exporter can handle Chromium encryption; inheriting the lifecycle and
    missing-profile handling keeps that path safe when the profile is absent.
    """

    def _find_cookies_db(self) -> Optional[Path]:
        candidates = (
            self.user_data_dir / "Network" / "Cookies",
            self.user_data_dir / "Cookies",
        )
        for path in candidates:
            if path.is_file():
                return path
        return None
